#!/usr/bin/env bash

# Invitilo: An command prompt
# Invitilo installer script
# Why not just use a standard distro packaging format?
# - Multiple packaging formats

set -euo pipefail

INSTALLER_VERSION="0.1.0"

# Check that the required external commands are available.
EXTERNAL_CMDS=(
    curl
    grep
    jq
    realpath
    sed
    sort
    tar
)

MISSING_CMDS=()
for cmd in "${EXTERNAL_CMDS[@]}"; do
    if ! command -v "$cmd" &> /dev/null; then
        MISSING_CMDS+=("$cmd")
    fi
done
# printf "Missing commands: ${MISSING_CMDS[*]}"
if [ ${#MISSING_CMDS[@]} -gt 0 ]; then
    S=""
    if [ ${#MISSING_CMDS[@]} -gt 1 ]; then
        S="s"
    fi
    printf "Please install the following command%s on your system:\n" "$S"
    for cmd in "${MISSING_CMDS[@]}"; do
        printf "  - %s\n" "$cmd"
    done
    exit 1
fi

GITHUB_REPO="leebehrens/invitilo"

INVITILO_INSTALL_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
INVITILO_INSTALL_FILE="$(basename "$(realpath "${BASH_SOURCE[0]}")")"

# Determine the user's config dir for Invitilo. Create it if it doesn't exist.
INVITILO_CONFIG_DIR="$HOME/.config/invitilo"
if [ -n "${XDG_CONFIG_HOME:-}" ] && [ -d "$XDG_CONFIG_HOME" ]; then
    INVITILO_CONFIG_DIR="$XDG_CONFIG_HOME/invitilo"
fi
mkdir -p "$INVITILO_CONFIG_DIR"
# Check that the directory was created successfully.
if [ ! -d "$INVITILO_CONFIG_DIR" ]; then
    printf "Error: Failed to create directory: %s\n" "$INVITILO_CONFIG_DIR"
    exit 1
fi

# Determine the user's bin and bin/download dir for Invitilo. Create them if they don't exist.
USER_BIN_DIR="$HOME/.local/bin"
if [ -n "${XDG_BIN_HOME:-}" ] && [ -d "$XDG_BIN_HOME" ]; then
    USER_BIN_DIR="$XDG_BIN_HOME"
fi
INVITILO_BIN_DIR="$USER_BIN_DIR/invitilo.d"
INVITILO_BIN_DOWNLOAD_DIR="$INVITILO_BIN_DIR/download"
mkdir -p "$INVITILO_BIN_DOWNLOAD_DIR"
# Check that the Invitilo bin/download directory chain was created successfully.
if [ ! -d "$INVITILO_BIN_DOWNLOAD_DIR" ]; then
    printf "Error: Failed to create directory: %s\n" "$INVITILO_BIN_DOWNLOAD_DIR"
    exit 1
fi

# Filenames for the get_xxxx_release functions.
HEADER_FILE="$INVITILO_BIN_DOWNLOAD_DIR/.header-"
DATA_FILE="$INVITILO_BIN_DOWNLOAD_DIR/.data-"

# Get the timestamp of the file, in seconds since epoch.
get_file_timestamp() {
    local file="$1"
    if [ -f "$file" ]; then
        local timestamp # seconds since epoch
        timestamp=$(stat -c %Y "$file")
        printf "%s" "$timestamp"
    else
        printf "0"
    fi
}

# Remove old files with hex suffixes; safer than rm -f "$XXXX_FILE"*
remove_old_files() {
    # Remove old files with hex suffixes; safer than rm -f "$XXXX_FILE"*
    for file in "$HEADER_FILE"*; do
        if [ -f "$file" ]; then
            rm "$file"
        fi
    done
    for file in "$DATA_FILE"*; do
        if [ -f "$file" ]; then
            rm "$file"
        fi
    done
}

# Check if the release file already exists locally.
# Returns 0 if the file exists, 1 if it doesn't.
is_release_file_exists() {
    local RELEASE="$1"
    local ASSET_NAME="$RELEASE.tar.gz"
    if [ -f "$INVITILO_BIN_DOWNLOAD_DIR/$ASSET_NAME" ]; then
        return 0
    else
        return 1
    fi
}

# Fetch the latest release version.
# GitHub's API returns the latest non-pre-release version.
do_get_latest_release() {
    remove_old_files
    local HEADER_FILE_PAGE="${HEADER_FILE}00"
    local DATA_FILE_PAGE="${DATA_FILE}00"
    local RELEASE
    curl -s \
        -H "Accept: application/vnd.github.v3+json" \
        -H "User-Agent: leebehrens" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -D "$HEADER_FILE_PAGE" \
        -o "$DATA_FILE_PAGE" \
        "https://api.github.com/repos/$GITHUB_REPO/releases/latest"
    RELEASE=$(jq -r '.tag_name' "$DATA_FILE_PAGE")
    if [ -z "$RELEASE" ]; then
        printf "Failed to fetch the latest release.\n"
        exit 1
    fi
    printf "%s" "$RELEASE"
}

# Fetch the latest release or pre-release version.
# GitHub's API does not guarantee ordering of pre-releases, so we need to get
# them all and find the newest one, retrieving by pages.
# GitHub will only return up to 1000 releases over multiple pages. But it's
# unlikely we'll have that many releases for Invitilo.
do_get_latest_prerelease() {
    remove_old_files
    local RELEASE=""
    local RELEASE_DATE="0001-01-01T00:00:00Z"
    local PAGE_NUM=0
    local NEXT_URL="https://api.github.com/repos/$GITHUB_REPO/releases?per_page=3"  # TODO: remove per_page or make max of 100
    while true; do
        local HEADER_FILE_PAGE
        HEADER_FILE_PAGE="$HEADER_FILE$(printf '%02x' "$PAGE_NUM")"
        local DATA_FILE_PAGE
        DATA_FILE_PAGE="$DATA_FILE$(printf '%02x' "$PAGE_NUM")"
        curl -s \
            -H "Accept: application/vnd.github.v3+json" \
            -H "User-Agent: leebehrens" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -D "$HEADER_FILE_PAGE" \
            -o "$DATA_FILE_PAGE" \
            "$NEXT_URL"
        IFS=" " read -r tag_name created_at < <(jq -r '.[] | "\(.tag_name) \(.created_at)"' "$DATA_FILE_PAGE" | sort -k2 -r | head -n 1)
        if [[ "$created_at" > "$RELEASE_DATE" ]]; then
            RELEASE="$tag_name"
            RELEASE_DATE="$created_at"
        fi
        # printf "."  # Cannot print anything for progress, because ends up as part of the returned RELEASE
        ((PAGE_NUM++))
        if (( PAGE_NUM > 5 )); then  # TODO: remove
            break
        fi
        NEXT_URL=$(grep -i '^link:' "$HEADER_FILE_PAGE" | sed -n 's/.*<\([^>]*\)>; rel="next".*/\1/p')
        if [ -z "$NEXT_URL" ]; then
            break
        fi
    done
    if [ -z "$RELEASE" ]; then
        printf "Failed to fetch the latest pre-release.\n"
        exit 1
    fi
    printf "%s" "$RELEASE"
}

# Fetch a specific release version.
# Technically, this isn't really required
do_get_specific_release() {
    local RELEASE_TAG="$1"
    remove_old_files
    local HEADER_FILE_PAGE="${HEADER_FILE}00"
    local DATA_FILE_PAGE="${DATA_FILE}00"
    local RELEASE
    curl -s \
        -H "Accept: application/vnd.github.v3+json" \
        -H "User-Agent: leebehrens" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -D "$HEADER_FILE_PAGE" \
        -o "$DATA_FILE_PAGE" \
        "https://api.github.com/repos/$GITHUB_REPO/releases/tags/$RELEASE_TAG"
    RELEASE=$(jq -r '.tag_name' "$DATA_FILE_PAGE")
    if [ -z "$RELEASE" ]; then
        printf "Failed to fetch the latest release.\n"
        exit 1
    fi
    printf "%s" "$RELEASE"
}

# Download the asset file (tarball) for the specified release.
# Note: From the header, it appears assets are available for only a year.
do_download_release_file() {
    local RELEASE="$1"
    printf "Downloading release file %s... " "$RELEASE"
    local ASSET_NAME="$RELEASE.tar.gz"
    local ASSET_HEADER_FILE="${HEADER_FILE}$RELEASE"
    local ASSET_FILE="$INVITILO_BIN_DOWNLOAD_DIR/$ASSET_NAME"

    # printf "ASSET_NAME:        %s\n" "$ASSET_NAME"
    # printf "ASSET_FILE:        %s\n" "$ASSET_FILE"
    # printf "ASSET_HEADER_FILE: %s\n" "$ASSET_HEADER_FILE"
    # printf "ASSET_URL:         %s\n" "https://github.com/$GITHUB_REPO/archive/refs/tags/$ASSET_NAME"

    curl -sL \
        -H "Accept: application/octet-stream" \
        -H "User-Agent: leebehrens" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        -D "$ASSET_HEADER_FILE" \
        -o "$ASSET_FILE" \
        "https://github.com/$GITHUB_REPO/archive/refs/tags/$ASSET_NAME"
        # This URL needs an ID number that is N/A, because only the installer is listed in the
        # list of assets for the release.
        # "https://github.com/$GITHUB_REPO/releases/assets/$ASSET_NAME"
    if [ $? -ne 0 ]; then
        printf "Failed\n"
        exit 1
    fi
    printf "Done\n"
}

# Unpack the release file
do_unpack_release_file() {
    local RELEASE="$1"
    local ASSET_NAME="$RELEASE.tar.gz"
    printf "Extracting release... "
    mkdir -p "$INVITILO_BIN_DIR/$RELEASE"
    tar -xzf "$INVITILO_BIN_DOWNLOAD_DIR/$ASSET_NAME" --strip-components=1 -C "$INVITILO_BIN_DIR/$RELEASE"
    if [ $? -ne 0 ]; then
        printf "Failed\n"
        exit 1
    fi
    printf "Done\n"
}

# Create a symlink to the specified release.
do_make_symlink() {
    local RELEASE="$1"
    printf "Creating symlink to Invitilo... "
    local SYMLINK_TARGET="$INVITILO_BIN_DIR/$RELEASE/invitilo"
    local SYMLINK="$USER_BIN_DIR/invitilo"
    # Ensure the target file exists before creating the symlink.
    if [ ! -f "$SYMLINK_TARGET" ]; then
        printf "Error: inivitilo %s not found.\n" "$RELEASE"
        exit 1
    fi
    # Remove the old symlink if it exists.
    if [ -f "$SYMLINK" ]; then
        rm "$SYMLINK"
    fi
    # Create the new symlink.
    ln -s "$SYMLINK_TARGET" "$SYMLINK"
    printf "Done\n"
}

# Download the release if necessary and install it.
do_process_release() {
    local RELEASE="$1"
    local FORCE_DOWNLOAD="$2"
    # local ASSET_NAME="$RELEASE.tar.gz"
    if $FORCE_DOWNLOAD || (! is_release_file_exists "$RELEASE"); then
        do_download_release_file "$RELEASE"
        if [ $? -ne 0 ]; then
            printf "Error: Failed to download the release file.\n"
            exit 1
        fi
    fi
    do_unpack_release_file "$RELEASE"
    do_make_symlink "$RELEASE"
}

# Show help.
do_help() {
    cat <<EOF
Invitilo installer

Usage: $0 [option] [release_tag]

option:
    --force      Force download
    -h, --help   Show this help message
    --version    Show version info of this installer and Invitilo

release_tag:
    latest       Download, install the latest release (default)
    prerelease   Download, install the latest release or pre-release
    v1.0.0       Download, install a specific release
EOF
}

# Show the version number of the installer and invitilo.
do_version() {
    printf "Invitilo installer %s\n" "$INSTALLER_VERSION"
    # Check for the symlink.
    if [ ! -L "$USER_BIN_DIR/invitilo" ]; then
        printf "Error: Symlink to invitilo not found"
        exit 1
    fi
    # Check for the VERSION file in the symlink target's directory.
    TARGET_DIR=$(dirname "$(readlink -f "$USER_BIN_DIR/invitilo")")
    if [ ! -f "$TARGET_DIR/VERSION" ]; then
        printf "Error: VERSION file not found in %s\n" "$TARGET_DIR"
        exit 1
    fi
    # Output the first line of the VERSION file.
    cat < "$TARGET_DIR/VERSION" | head -n 1
}


# Handle options.
FORCE_DOWNLOAD=false
OPTION="${1:-}"
if [[ "$OPTION" =~ ^- ]]; then
    case "$1" in
        --force)
            FORCE_DOWNLOAD=true
            shift
            ;;
        -h|--help)
            do_help
            exit 0
            ;;
        --version)
            do_version
            exit 0
            ;;
        *)
            printf "Error: invalid option '%s'. Use %s -h for help.\n" "$1" "$0"
            exit 1
            ;;
    esac
fi

# Handle release tag (use "latest" if none specified)
if [ "$#" -gt 1 ]; then
    printf "Error: too many arguments. Use %s -h for help.\n" "$0"
    exit 1
fi
RELEASE_TAG="${1:-latest}"
case "$RELEASE_TAG" in
    latest)
        printf "Installing the latest release..."
        RELEASE=$(do_get_latest_release)
        if [ $? -ne 0 ]; then
            printf "Error: Failed to fetch the latest release.\n"
            exit 1
        fi
        do_process_release "$RELEASE" "$FORCE_DOWNLOAD"
        printf "Release: %s\n" "$RELEASE"
        # Logic for installing the latest release is already handled above
        ;;
    prerelease)
        printf "Installing the latest pre-release..."
        RELEASE=$(do_get_latest_prerelease)
        if [ $? -ne 0 ]; then
            printf "Error: Failed to fetch the latest release.\n"
            exit 1
        fi
        do_process_release "$RELEASE" "$FORCE_DOWNLOAD"
        printf "Release: %s\n" "$RELEASE"
        # Logic for installing the latest pre-release is already handled above
        ;;
    v*)
        printf "Installing release version %s..." "$RELEASE_TAG"
        RELEASE=$(do_get_specific_release "$RELEASE_TAG")
        if [ $? -ne 0 ]; then
            printf "Error: Failed to fetch the release.\n"
            exit 1
        fi
        do_process_release "$RELEASE" "$FORCE_DOWNLOAD"
        printf "Release: %s\n" "$RELEASE"
        # Logic for installing a specific release is already handled above
        ;;
    *)
        printf "Error: invalid release tag '%s'. Use %s -h for help." "$RELEASE_TAG" "$0"
        exit 1
        ;;
esac
