name: Tag new versions
on:
  push:
    branches:
      - main

jobs:
  tag-new-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Detect and Tag New Version
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            head -n 1 "${INVITILO_ROOT_DIR}/VERSION" | (IFS=' ' read -r _ second_field ; echo "$second_field")
          create-tag: true
          tag-template: v{VERSION}
          tag-annotation-template: ""
